# Generated by Django 5.2.1 on 2025-06-11 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_declined',
            field=models.BooleanField(default=False),
        ),
    ]
